spring:
  application:
    name: rutina-backend

  datasource:
    url: ${DB_URL}?prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# 제미나이 사용
#  ai:
#    google:
#      genai:
#        api-key: ${OPENAI_API_KEY}
#        chat:
#          options:
#            model: gemini-2.5-flash

# OpenAI 사용
  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 1800000       # 30분
  refresh-token-expiry: 604800000    # 7일