spring:
  application:
    name: rutina-backend

# db 연결 안 해서 일단 다 비활성화 함.
  datasource:
    url: ''
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

# ai 연결 안 해서 일단 임시값
  ai:
    openai:
      api-key: "dummy"