-- 유저 테이블
CREATE TABLE public.users (
                              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              email character varying NOT NULL UNIQUE,
                              password character varying,
                              nickname character varying NOT NULL,
                              age character varying,
                              role character varying,
                              gender integer DEFAULT 0,
                              provider character varying NOT NULL,
                              provider_id character varying,
                              created_at timestamp with time zone NOT NULL DEFAULT now(),
                              updated_at timestamp with time zone NOT NULL DEFAULT now(),
                              deleted_at timestamp with time zone
);

-- 카테고리 테이블
CREATE TABLE public.categories (
                                   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   user_id bigint NOT NULL,
                                   name character varying NOT NULL,
                                   color_code character varying NOT NULL,
                                   rt_sum character varying NOT NULL,
                                   sort_order integer NOT NULL DEFAULT 0,
                                   created_at timestamp with time zone NOT NULL DEFAULT now(),
                                   updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                   CONSTRAINT rt_categories_user_id_fkey
                                       FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- 루틴 테이블
CREATE TABLE public.routines (
                                 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id bigint NOT NULL,
                                 category_id bigint,
                                 title character varying NOT NULL,
                                 alarm boolean NOT NULL DEFAULT false,
                                 state boolean NOT NULL DEFAULT true,
                                 cron_expression character varying,
                                 start_time time without time zone,
                                 end_time time without time zone,
                                 created_at timestamp with time zone NOT NULL DEFAULT now(),
                                 updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                 CONSTRAINT rt_routines_user_id_fkey
                                     FOREIGN KEY (user_id) REFERENCES public.users(id),
                                 CONSTRAINT rt_routines_category_id_fkey
                                     FOREIGN KEY (category_id) REFERENCES public.categories(id)
);

-- 날짜별 목표 기록 테이블
CREATE TABLE public.daily_targets (
                                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      routine_id bigint NOT NULL,
                                      target_date date NOT NULL,
                                      is_completed boolean NOT NULL DEFAULT false,
                                      created_at timestamp with time zone NOT NULL DEFAULT now(),
                                      updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                      CONSTRAINT rt_daily_targets_routine_id_fkey
                                          FOREIGN KEY (routine_id) REFERENCES public.routines(id)
);

-- 로그인용 토큰
CREATE TABLE public.refresh_tokens (
                                       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id bigint NOT NULL,
                                       token_value text NOT NULL,
                                       expires_at timestamp with time zone NOT NULL,
                                       created_at timestamp with time zone NOT NULL DEFAULT now(),
                                       updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                       CONSTRAINT rt_refresh_tokens_user_id_fkey
                                           FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- AI 프롬포트 테이블
CREATE TABLE public.ai_logs (
                                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id bigint NOT NULL,
                                routine_id bigint,
                                request_type character varying NOT NULL,
                                prompt text NOT NULL,
                                response text NOT NULL,
                                created_at timestamp with time zone NOT NULL DEFAULT now(),
                                updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                CONSTRAINT rt_ai_logs_user_id_fkey
                                    FOREIGN KEY (user_id) REFERENCES public.users(id),
                                CONSTRAINT rt_ai_logs_routine_id_fkey
                                    FOREIGN KEY (routine_id) REFERENCES public.routines(id)
);