----------------------------------------
-- 로그인용 토큰 테이블에 device 컬럼 추가 --
----------------------------------------

-- 유저 테이블
CREATE TABLE public.users (
                              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              email varchar(100) NOT NULL UNIQUE,
                              password varchar(255),
                              nickname varchar(30) NOT NULL,
                              age varchar(10),
                              role varchar(20),
                              gender integer DEFAULT 0,
                              provider varchar(20) NOT NULL,
                              provider_id varchar(100),
                              created_at timestamp with time zone NOT NULL DEFAULT now(),
                              updated_at timestamp with time zone NOT NULL DEFAULT now(),
                              deleted_at timestamp with time zone
);

-- 카테고리 테이블
CREATE TABLE public.categories (
                                   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   user_id bigint NOT NULL,
                                   name varchar(20) NOT NULL,
                                   color_code varchar(7) NOT NULL,
                                   rt_sum varchar(10) NOT NULL,
                                   sort_order integer NOT NULL DEFAULT 0,
                                   created_at timestamp with time zone NOT NULL DEFAULT now(),
                                   updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                   CONSTRAINT rt_categories_user_id_fkey
                                       FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- 루틴 테이블
CREATE TABLE public.routines (
                                 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id bigint NOT NULL,
                                 category_id bigint,
                                 title varchar(30) NOT NULL,
                                 alarm boolean NOT NULL DEFAULT false,
                                 state boolean NOT NULL DEFAULT true,
                                 cron_expression varchar(100),
                                 start_time time without time zone,
                                 end_time time without time zone,
                                 created_at timestamp with time zone NOT NULL DEFAULT now(),
                                 updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                 CONSTRAINT rt_routines_user_id_fkey
                                     FOREIGN KEY (user_id) REFERENCES public.users(id),
                                 CONSTRAINT rt_routines_category_id_fkey
                                     FOREIGN KEY (category_id) REFERENCES public.categories(id)
);

-- 날짜별 목표 기록 테이블
CREATE TABLE public.daily_targets (
                                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      routine_id bigint NOT NULL,
                                      target_date date NOT NULL,
                                      is_completed boolean NOT NULL DEFAULT false,
                                      created_at timestamp with time zone NOT NULL DEFAULT now(),
                                      updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                      CONSTRAINT rt_daily_targets_routine_id_fkey
                                          FOREIGN KEY (routine_id) REFERENCES public.routines(id)
);

-- 로그인용 토큰
CREATE TABLE public.refresh_tokens (
                                       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id bigint NOT NULL,
                                       token_value varchar(5000) NOT NULL,
                                       device character varying,
                                       expires_at timestamp with time zone NOT NULL,
                                       created_at timestamp with time zone NOT NULL DEFAULT now(),
                                       updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                       CONSTRAINT rt_refresh_tokens_user_id_fkey
                                           FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- AI 프롬포트 테이블
CREATE TABLE public.ai_logs (
                                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id bigint NOT NULL,
                                routine_id bigint,
                                request_type varchar(30) NOT NULL,
                                prompt varchar(5000) NOT NULL,
                                response varchar(5000) NOT NULL,
                                created_at timestamp with time zone NOT NULL DEFAULT now(),
                                updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                CONSTRAINT rt_ai_logs_user_id_fkey
                                    FOREIGN KEY (user_id) REFERENCES public.users(id),
                                CONSTRAINT rt_ai_logs_routine_id_fkey
                                    FOREIGN KEY (routine_id) REFERENCES public.routines(id)
);